const Constants = {
  CONFIG_PREFIX: 'boj-extended-',
  CONFIG_SHOW_GROUP_LINK: 'show-group-link',
  CONFIG_SHOW_STATUS_HISTORY: 'show-status-history',
  CONFIG_SHOW_STATUS_PID: 'show-status-pid',
  CONFIG_SHOW_STATUS_PTITLE: 'show-status-ptitle',
  CONFIG_SHOW_FAKE_RESULT: 'show-fake-result',
  CONFIG_SHOW_USER_TIER: 'show-user-tier',
  CONFIG_SHOW_USER_DECO: 'show-user-decorations',
  CONFIG_SHOW_PROBLEM_ID: 'show-pid',
  CONFIG_SHOW_PROBLEM_TITLE: 'show-pname',
  CONFIG_SHOW_PROBLEM_TIER: 'show-problem-tier',
  CONFIG_SHOW_PROBLEM_TIER_COLOR: 'show-problem-tier-color',
  CONFIG_FONT_STYLE: 'font-style',
  CONFIG_THEME: 'theme',
  CONFIG_THEME_IMAGE_FILTER: 'theme-image-filter',
  CONFIG_WIDE: 'wide',
  CONFIG_LOCATION_HISTORY: 'location-history',
  CONFIG_LOCATION_EXPIRE_MS: 4 * 1000 * 3600,
  STORAGE_PREFIX: 'boj-extended-local-',
  STORAGE_STATUS_HISTORY: 'boj-extended-local-status-history',
  QUICK_SEARCH_URL: 'https://aewewtnd4p-dsn.algolia.net/1/indexes/*/queries',
  QUICK_SEARCH_QUERY:
    'x-algolia-agent=Algolia%20for%20JavaScript%20(3.33.0)%3B%20Browser%20(lite)%3B%20JS%20Helper%20(2.28.0)&x-algolia-application-id=AEWEWTND4P&x-algolia-api-key=40fa3b88d4994a18f89e692619c9f3f3',
  BG_DB_PROBLEMS: 'boj-extended-DB-PROBLEMS',
  BG_PROBLEM_FETCH_URL:
    'https://raw.githubusercontent.com/joonas-yoon/boj-extended/release/db/v1.1.json',
  THEMES: {
    // auto: '시스템 설정',
    light: '밝은 테마',
    dark: '어두운 테마',
    rigel: 'Rigel',
  },
};
