name: Bot

on:
  schedule:
    # every 4:00 am, everyday in UTC+9
    # but 7:00 pm, everyday in UTC
    - cron: '0 19 * * *'
  workflow_dispatch:
    inputs:
      update:
        description: 'Run bot'
        required: true
        default: 'Run bot in manually'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'release'

    - name: Set up python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install python package
      run: pip install requests

    - name: Run bot
      run: python ./util/bot.py

    - name: Lint
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: |
        npm ci
        npm run lint

    - name: Commit report
      run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'joo-na@users.noreply.github.com'
          git add -N db
          git diff db > git.diff
          [ -s git.diff ] && git add db && git commit -m ":construction_worker: automatically updated" && git push || echo "Skip commit"
