name: build and deploy

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["build"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      update:
        description: "deploy"
        required: true
        default: "Deploy"

jobs:
  deploy:
    if: ${{ contains(github.ref, 'main') || contains(github.event.head_commit.message, '[deploy]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./dist

      - name: Install chrome-webstore-upload-cli
        run: npm install -g chrome-webstore-upload-cli

      - name: Upload extension to Chrome Web Store
        run: >
          npx chrome-webstore-upload-cli upload
          --extension-id ${{ secrets.EXTENSION_ID }}
          --client-id ${{ secrets.CLIENT_ID }}
          --client-secret ${{ secrets.CLIENT_SECRET }}
          --refresh-token ${{ secrets.REFRESH_TOKEN }}
          --source dist
